[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Adam Goldsmith", email = "adam@adamgoldsmith.name"},
]
dependencies = [
    "aprs3~=8.0",
    "aiohttp~=3.8",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool]
[tool.pdm]

[tool.black]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
